### ISSUE TITLE
python.exe : The command parameter was already specified

### ISSUE THREAD

**Issue by gauravg84** [0xZDH/BridgeKeeper#2]
Hello,

I am trying to run the program; however, it keeps on getting "**python.exe : The command parameter was already specified"**.

I am using the following command:
Python G:\Tools\BridgeKeeper-master\bridgekeeper.py --company "Example Ltd." --format {f}{last}@example.com --depth 10 --output example-employees/ --debug

I really appreciate any help you can provide.

Gaurav

**Comment by infoescdub** [comment]
Had the same issue. Use Quote brackets 
G:\Tools\BridgeKeeper-master\bridgekeeper.py --company "Example Ltd." --format "{f}{last}@example.com" --depth 10 --output example-employees/ --debug

**Comment by 0xZDH** [comment]
Assuming this issue is resolved via the latest comment: wrapping the `--format` value in double quotes.

If this issue persists, re-open this issue I will take a look.
